import Navbar from './Navbar'
import Footer from './Footer'
import Head from 'next/head'

const Layout = ( {children} ) => {
    return  (
        <>
        <Head>
            <title>PLNT Webshop</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            {/* <link rel="icon" href="https://plnts.com/favicon.ico" /> */}
          </Head>

        <div>
            <Navbar/>
                <div id="plnts-contents" className='my-20'>
                    {children}
                </div>
            <Footer/>
        </div>
        </>

    )
}

export default Layout;