import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

// import React, { useState, useContext } from 'react';
// import { Context } from "../context";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let imgUrl = "https://plnts.com/_next/image?url=https%3A%2F%2Fwebshop.plnts.com%2Fmedia%2Fwysiwyg%2Fbanners%2FBanner_Interieur_Lowress.jpg&w=1920&q=75"
  // const { state, dispatch } = useContext(Context);
  return (
    <>
      <Head>
        <title>PLNT Webshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="icon" href="https://plnts.com/favicon.ico" /> */}
      </Head>

      <div className="text-4xl m-2">Welcome to PLNTS!</div>
      <img id="home-banner" src={imgUrl} height="40px"/>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        {/* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. */}
      </p>

      <div>          
        <Link className='font-bold' href="webshop">
          <button className="text-white bg-yellow-500 p-2 p-l-4 p-r-4 my-4 rounded-3xl" > Check out our Webshop</button>
        </Link>
      </div>
      
      {/* <div>
          Check out our 
          <Link className='font-bold' href="webshop">
            <button>Webshop</button>
            </Link> for more gifts!
      </div> */}
      


      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      {/* <div>
        <p>index page</p>
        <button onClick={() => dispatch({ type: "LOGGED_IN_USER", payload: "Ryan Dhungel" }) } > login </button>
        <button onClick={() => dispatch({ type: "LOGGED_IN_USER", payload: null })} > logout </button>
        {JSON.stringify(state)}
      </div> */}
    </>
  )
}
